#stdlib
from ctypes import *

#mylib
from . import GWArray, Vec3f


class WorldContext(Structure):
	_fields_ = [
		("account_info", c_void_p),
		("message_buff", GWArray),
		("dialog_buff", GWArray),
		("merch_items", GWArray),					# Item Array of currently-interacted merchant
		("merch_items2", GWArray),					# no fucking clue
		("accum_map_init_unk0", c_uint32),
		("accum_map_init_unk1", c_uint32),
		("accum_map_init_offset", c_uint32),
		("accum_map_init_length", c_uint32),
		("h0054", c_uint32),
		("accum_map_init_unk2", c_uint32),
		("h005C", c_uint32),
		("map_agents", GWArray),
		("party_allies", GWArray),
		("all_flag", Vec3f),
		("h00A8", c_uint32),
		("attributes", GWArray),
		("h00BC", c_uint32 * 255),
		("h04B8", GWArray),
		("h04C8", GWArray),
		("h04D8", c_uint32),
		("h04DC", GWArray),
		("h04EC", c_uint32 * 7),
		("party_effects", GWArray),
		("h0518", GWArray),
		("active_quest_id", c_uint32),
		("quest_log", GWArray),
		("h053C", c_uint32 * 10),
		("mission_objectives", GWArray),
		("henchmen_agent_ids", GWArray),
		("hero_flags", GWArray),
		("hero_info", GWArray),
		("cartographed_areas", GWArray),
		("h05B4", c_uint32 * 2),
		("controlled_minion_count", GWArray),
		("missions_completed", GWArray),
		("missions_bonus", GWArray),
		("missions_completed_hm", GWArray),
		("missions_bonus_hm", GWArray),
		("unlocked_map", GWArray),
		("h061C", c_uint32 * 2),
		("player_morale_info", c_void_p),
		("h028C", c_uint32),
		("party_morale_related", GWArray),
		("h063C", c_uint32 * 16),
		("player_number", c_uint32),
		("player_controlled_character", c_void_p),
		("is_hard_mode_unlocked", c_uint32),
		("h0688", c_uint32 * 2),
		("salvage_session_id", c_uint32),
		("h0694", c_uint32 * 5),
		("player_team_token", c_uint32),
		("pets", GWArray),
		("party_profession_states", GWArray),
		("h06CC", GWArray),
		("h06DC", c_uint32),
		("h06E0", GWArray),
		("skillbar", GWArray),
		("learnable_character_skills", GWArray),
		("unlocked_character_skills", GWArray),
		("duplicated_character_skills", GWArray),
		("h0730", GWArray),
		("experience", c_uint32),
		("experience_dupe", c_uint32),
		("current_kurzick", c_uint32),
		("current_kurzick_dupe", c_uint32),
		("total_earned_kurzick", c_uint32),
		("total_earned_kurzick_dupe", c_uint32),
		("current_luxon", c_uint32),
		("current_luxon_dupe", c_uint32),
		("total_earned_luxon", c_uint32),
		("total_earned_luxon_dupe", c_uint32),
		("current_imperial", c_uint32),
		("current_imperial_dupe", c_uint32),
		("total_earned_imperial", c_uint32),
		("total_earned_imperial_dupe", c_uint32),
		("unk_faction4", c_uint32),
		("unk_faction4_dupe", c_uint32),
		("unk_faction5", c_uint32),
		("unk_faction5_dupe", c_uint32),
		("level", c_uint32),
		("level_dupe", c_uint32),
		("morale", c_uint32),
		("morale_dupe", c_uint32),
		("current_balth", c_uint32),
		("current_balth_dupe", c_uint32),
		("total_earned_balth", c_uint32),
		("total_earned_balth_dupe", c_uint32),
		("max_kurzick", c_uint32),
		("max_luxon", c_uint32),
		("max_balth", c_uint32),
		("max_imperial", c_uint32),
		("equipment_status", c_uint32),
		("agent_infos", GWArray),
		("h07DC", GWArray),
		("mission_map_icons", GWArray),
		("npcs", GWArray),
		("players", GWArray),
		("titles", GWArray),
		("title_tiers", GWArray),
		("vanquished_areas", GWArray),
		("foes_killed", c_uint32),
		("foes_to_kill", c_uint32),
	]


